  name: first workflow

  on:
   push:
    branches:
      - main 

  jobs:
   firstjob: 
    runs-on: ubuntu-latest

    steps:
     - name: first steps print
       run: echo " push is done !!!!!!!!!!  "
       
         
        
        
    

  
